backend:
  name: github
  repo: B3lk00/AMEA-Tech-web-new
  branch: main

  # decap oauth proxy (worker)
  base_url: https://decap-auth-new.belmins1617.workers.dev
  auth_endpoint: auth

  # GitHub API (nekad Decap bez ovoga "zapne")
  api_root: https://api.github.com

  # tvoj sajt (pomaže kod origin/callback tokova)
  site_url: https://amea-tech-web-new.pages.dev

# (opcionalno) ako želiš uredniji flow u timu
publish_mode: editorial_workflow


media_folder: "images/oglasi"
public_folder: "/images/oglasi"

collections:
  - name: "oglasi"
    label: "Oglasi"
    folder: "oglasi"
    create: true
    slug: "{{kategorija}}-{{slug}}-{{year}}{{month}}{{day}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Kategorija", name: "kategorija", widget: "select", options: ["racunari","laptopi","monitori","toneri"] }
      - { label: "Naziv", name: "naziv", widget: "string" }
      - { label: "Cijena", name: "cijena", widget: "string", required: false }
      - { label: "Stanje", name: "stanje", widget: "select", options: ["Novo","Polovno"], required: false }
      - { label: "Opis", name: "opis", widget: "text", required: false }
      - { label: "Specifikacije", name: "spec", widget: "list", required: false }
      - label: "Slike"
        name: "slike"
        widget: "list"
        field: { label: "Slika", name: "image", widget: "image" }
        required: false
